name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy directly from the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Use the Node.js version your project requires

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build  # Replace with your build command (e.g., vite build)

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist  # Output folder after building
        publish_branch: gh-pages  # Create and deploy to gh-pages branch
